### ISSUE TITLE
Pré-calcular conversão da imagem para padrões de LEDs

### ISSUE THREAD

**Issue by felipesanches** [eduoda/paudeled#1]
Aqui você amostra a imagem com base no ângulo atual a todo instante:
https://github.com/eduoda/paudeled/blob/master/paudeled.ino#L69-L75

Seria mais eficiente criar durante o setup uma matriz de dados com o padrão de LEDs indexado por valor de ângulo (um dos muitos setores possíveis na resolução escolhida) e depois no momento da interrupção só cuspir para a SPI o dado já antes mastigado (essa frase ficou linda :-P)...

**Comment by eduoda** [comment]
aff, esse ai ta velho, pera, vou te mandar o ultimo

## 

## Oda

If you don't have time to do it right, where

## are you going to find the time to do it over?

2016-04-26 11:39 GMT-03:00 Felipe Corrêa da Silva Sanches <
notifications@github.com>:

**Comment by eduoda** [comment]
pronto, codigo meio zoneado, mas acho que faz mais ou menos o que vc falou, de todo jeito, nao eh uma boa pq a ideia eh trocar as imgs, tenho uma outra versao aqui, mas ainda nao foi testada, vou abrir uma branch.
